// common exception codes
export const INVALID_DATA_TYPE_EXCEPTION = 'STP-EXCEPTION-0001';

// exception codes related to simple data types
export const SIMPLE_DATA_INVALID_EXPECTED_STRING_WIDTH_EXCEPTION =
  'STP-EXCEPTION-0002';
export const SIMPLE_DATA_REAL_PRECISION_NOT_ALLOWED_EXCEPTION =
  'STP-EXCEPTION-0003';
export const SIMPLE_DATA_STRING_WIDTH_NOT_ALLOWED_EXCEPTION =
  'STP-EXCEPTION-0004';

// exception codes related to aggregation data types
export const AGGREGATION_TYPE_LOWER_INDEX_MUST_BE_LESS_THAN_UPPER_INDEX_EXCEPTION =
  'STP-EXCEPTION-0005';
export const AGGREGATION_TYPE_INVALID_BOUND_EXCEPTION = 'STP-EXCEPTION-0006';
export const AGGREGATION_TYPE_OUT_OF_BOUNDS_EXCEPTION = 'STP-EXCEPTION-0007';
