// common exception codes
export const INVALID_DATA_TYPE_EXCEPTION = 'STP-EXCEPTION-0001';

// exception codes related to simple data types
export const SIMPLE_DATA_MAX_LENGTH_EXCEEDED_EXCEPTION = 'STP-EXCEPTION-0002';
export const SIMPLE_DATA_REAL_PRECISION_NOT_ALLOWED_EXCEPTION =
  'STP-EXCEPTION-0003';
export const SIMPLE_DATA_STRING_MAX_LENGTH_NOT_ALLOWED_EXCEPTION =
  'STP-EXCEPTION-0004';

// exception codes related to aggregation data types
export const AGGREGATION_BELOW_LOWER_BOUND_EXCEPTION = 'STP-EXCEPTION-0005';
export const AGGREGATION_EXCEEDED_UPPER_BOUND_EXCEPTION = 'STP-EXCEPTION-0006';
export const AGGREGATION_INVALID_BOUND_EXCEPTION = 'STP-EXCEPTION-0007';
